version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # JavaScript dependencies in Tauri app
  - package-ecosystem: "npm"
    directory: "/WORKINPROGRESS/tauri-desktop-app"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
